
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/build-blog-index.mts

export type BlogPost = {
  slug: string
}

export const ALL_POSTS: BlogPost[] = [
  {
    "slug": "The-Wrapper-Era-Ended-On-A-Contract-Clause"
  },
  {
    "slug": "The-Mental-Models-That-Poison-Founders"
  },
  {
    "slug": "KISS-or-Die"
  }
];
