
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/build-blog-index.mts

export type BlogPost = {
  slug: string
}

export const ALL_POSTS: BlogPost[] = [
  {
    "slug": "Vibe-Coding-Made-Computer-Science-More-Important"
  },
  {
    "slug": "VC-Is-Quietly-Drawing-The-Post-Agent-Stack"
  },
  {
    "slug": "The-Wrapper-Era-Ended-On-A-Contract-Clause"
  },
  {
    "slug": "The-Model-Got-Better-The-Environment-Had-To-Catch-Up"
  },
  {
    "slug": "The-Mental-Models-That-Poison-Founders"
  },
  {
    "slug": "KISS-or-Die"
  },
  {
    "slug": "Instinct-Can-Build-AIs-Next-Great-Moat"
  },
  {
    "slug": "Context-Windows-Are-RAM-Not-Memory"
  },
  {
    "slug": "Autonomous-Agents-Need-Constitutions-Not-Bigger-Contexts"
  }
];
