// scripts/build-blog-index.mts
import fs from "node:fs"
import path from "node:path"
import { glob } from "glob"

type Metadata = {
  title: string
  publishedAt: string
  summary: string
  image?: string
}

function parseFrontmatter(fileContent: string) {
  const frontmatterRegex = /---\s*([\s\S]*?)\s*---/
  const match = frontmatterRegex.exec(fileContent)

  if (!match) {
    throw new Error("Frontmatter block not found")
  }

  const frontMatterBlock = match[1]
  const content = fileContent.replace(frontmatterRegex, "").trim()
  const frontMatterLines = frontMatterBlock.trim().split("\n")
  const metadata: Partial<Metadata> = {}

  for (const line of frontMatterLines) {
    const [key, ...valueArr] = line.split(": ")
    let value = valueArr.join(": ").trim()
    value = value.replace(/^['"](.*)['"]$/, "$1") // Remove quotes
    metadata[key.trim() as keyof Metadata] = value
  }

  return { metadata: metadata as Metadata, content }
}

const ROOT = process.cwd()
const BLOG_DIR = path.join(ROOT, "app", "blog")
const OUT_FILE = path.join(ROOT, "app", "blog", "posts.generated.ts")

function buildIndex() {
  const files = glob.sync("**/*.mdx", { cwd: BLOG_DIR })

  const posts = files.map((file: string) => {
    const fullPath = path.join(BLOG_DIR, file)
    const raw = fs.readFileSync(fullPath, "utf8")
    const { metadata, content } = parseFrontmatter(raw)
    const slug = path.basename(path.dirname(file))

    return { slug, metadata, content }
  })

  const fileContents = `
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/build-blog-index.mts

export type Metadata = {
  title: string
  publishedAt: string
  summary: string
  image?: string
}

export type BlogPost = {
  slug: string
  metadata: Metadata
  content: string
}

export const ALL_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`

  fs.writeFileSync(OUT_FILE, fileContents, "utf8")
  // eslint-disable-next-line no-console
  console.log(`✅ Blog index generated at ${path.relative(ROOT, OUT_FILE)}`)
}




buildIndex()



