// scripts/build-blog-index.mts
import fs from "node:fs"
import path from "node:path"
import { glob } from "glob"


const ROOT = process.cwd()
const BLOG_DIR = path.join(ROOT, "posts")
const OUT_FILE = path.join(ROOT, "lib", "posts-runtime", "posts.generated.ts")

function buildIndex() {
  const files = glob.sync("**/*.mdx", { cwd: BLOG_DIR })

  const posts = files.map((file: string) => {
    const fullPath = path.join(BLOG_DIR, file)
    const raw = fs.readFileSync(fullPath, "utf8")
    const slug = path.basename(file, ".mdx")

    return { slug }
  })

  const fileContents = `
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/build-blog-index.mts

export type BlogPost = {
  slug: string
}

export const ALL_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`

  fs.writeFileSync(OUT_FILE, fileContents, "utf8")
  // eslint-disable-next-line no-console
  console.log(`✅ Blog index generated at ${path.relative(ROOT, OUT_FILE)}`)
}




buildIndex()



